version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  identity.api:
    image: samples/identityapi.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.Api/Dockerfile
    depends_on:
      - sql.data